version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jobber-postgres
    environment:
      POSTGRES_DB: jobber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8100251810
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jobber-api:
    build: .
    container_name: jobber-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/Jobber
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8100251810
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_USERNAME: jinjahub11@gmail.com
      SPRING_MAIL_PASSWORD: opthkrivlbjntpkp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

volumes:
  pgdata: